### ISSUE TITLE
Preparing statements with parametrised limit

### ISSUE THREAD

**Issue by viraptor** [sfackler/rust-postgres#152]
I'm running into an issue when trying to prepare a select like this:
```
fn _get_videos(connection: &PooledConnection<PostgresConnectionManager>, approved: bool, limit: i32) -> Vec<Video> {
    let stmt = connection.prepare("SELECT video_id, name, year, event_id, style FROM video WHERE approved=$1 LIMIT $2").unwrap();
    let rows = stmt.query(&[&approved, &limit]).unwrap();                                           
    rows.iter().map(|row| Video::from(&row)).collect()  
```

Even at debug logging, the result is just:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: WrongType(Int8)', ../src/libcore/result.rs:738
stack backtrace:
   ...........
   7:     0x55e9afc8041f - panicking::panic_fmt::h4c8d12e3c05f3b8cZEK
   8:     0x55e9af762766 - result::_<impl>::unwrap::unwrap::h6094937477412054960
                        at ../src/libcore/macros.rs:28
   9:     0x55e9af767ab4 - database::_get_videos::he940e4dacfb35bd03ba
                        at src/database.rs:29
```

I'm not sure if this is an issue in my code and a bad error report, or something actually wrong in rust-postgres.

**Comment by sfackler** [comment]
Postgres is giving the type `INT8` to the limit parameter, which corresponds to `i64` in Rust, not `i32`.
