### ISSUE TITLE
"url: Invalid character in scheme." when trying to connect

### ISSUE THREAD

**Issue by rjgoldsborough** [sfackler/rust-postgres#200]
Howdy,

I am trying to compile the https://github.com/rust-lang/crates.io backend.
When running a db migration I get an error when trying to connect to postgres

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectParams(StringError("url: Invalid character in scheme."))', ../src/libcore/result.rs:789
```

The backtrace is
```
stack backtrace:
   1:     0x7fd6a9bae4f3 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7fd6a9bb155d - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7fd6a9bb0890 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7fd6a9bb0de8 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7fd6a9bb0c82 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7fd6a9bb0bc0 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7fd6a9bb0b41 - rust_begin_unwind
   8:     0x7fd6a9beb74f - core::panicking::panic_fmt::hc5789f4e80194729
   9:     0x7fd6a99730a2 - core::result::unwrap_failed::h65351e0da6613351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x7fd6a996cc21 - _<core..result..Result<T, E>>::unwrap::hbb69348fa5958082
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:727
  11:     0x7fd6a998c7cd - migrate::main::h26e8889f6fcdab56
                        at /home/ducks/devel/rust/crates.io/src/bin/migrate.rs:17
  12:     0x7fd6a9bb9026 - __rust_maybe_catch_panic
  13:     0x7fd6a9bb0101 - std::rt::lang_start::h352a66f5026f54bd
  14:     0x7fd6a999f0c3 - main
  15:     0x7fd6a84f4b44 - __libc_start_main
  16:     0x7fd6a9962ea8 - <unknown>
  17:                0x0 - <unknown>
```

The database url I am using is
```
postgres://postgres@localhost/cargo_registry
```

I really can't seem to see what in the scheme is invalid so any insight or ideas would be greatly appreciated and lemme know what else I can provide.

Thanks in advance!

**Comment by rjgoldsborough** [comment]
It gets called here
https://github.com/rust-lang/crates.io/blob/master/src/bin/migrate.rs#L17

**Comment by sfackler** [comment]
That seems like a reasonable connection string - are there any weird zero-width unicode characters in there or anything like that? The logic that's producing that error is here: https://github.com/sfackler/rust-postgres/blob/master/src/url.rs#L204

**Comment by rjgoldsborough** [comment]
Yeah I've read that function a few times now to make sure I wasn't missing anything. 

Not that I can tell. I copied the string suggestion, deleted then hand typed it. I try removing it and it breaks worse so I know it's being used. 

I guess I will continue to poke around. Thanks.

**Comment by rjgoldsborough** [comment]
I might have made a little progress.

In that module, the database url is set as an env var and uses cargo_registry::env to populate that.
https://github.com/rust-lang/crates.io/blob/master/src/bin/migrate.rs#L17

If I remove that and use the raw string I get a new error.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectParams(StringError("a password was requested but not provided"))', ../src/libcore/result.rs:789
stack backtrace:
   1:     0x7f574927f213 - std::sys::backtrace::tracing::imp::write::h482d45d91246faa2
   2:     0x7f574928227d - std::panicking::default_hook::_{{closure}}::h89158f66286b674e
   3:     0x7f57492815b0 - std::panicking::default_hook::h9e30d428ee3b0c43
   4:     0x7f5749281b08 - std::panicking::rust_panic_with_hook::h2224f33fb7bf2f4c
   5:     0x7f57492819a2 - std::panicking::begin_panic::hcb11a4dc6d779ae5
   6:     0x7f57492818e0 - std::panicking::begin_panic_fmt::h310416c62f3935b3
   7:     0x7f5749281861 - rust_begin_unwind
   8:     0x7f57492bc32f - core::panicking::panic_fmt::hc5789f4e80194729
   9:     0x7f5749124972 - core::result::unwrap_failed::h65351e0da6613351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x7f574911e4f1 - _<core..result..Result<T, E>>::unwrap::hbb69348fa5958082
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/result.rs:727
  11:     0x7f574913e057 - migrate::main::h26e8889f6fcdab56
                        at /home/ducks/devel/rust/crates.io/src/bin/migrate.rs:16
  12:     0x7f5749289d46 - __rust_maybe_catch_panic
  13:     0x7f5749280e21 - std::rt::lang_start::h352a66f5026f54bd
  14:     0x7f5749150933 - main
  15:     0x7f5747cabb44 - __libc_start_main
  16:     0x7f5749114778 - <unknown>
  17:                0x0 - <unknown>
```

**Comment by sfackler** [comment]
You'll need to provide a password in the URL then: `postgres://username:password@localhost/dbname`.

**Comment by rjgoldsborough** [comment]
Closing this. Thanks for help.
