### ISSUE TITLE
tokio_postgres::Connection::execute hangs undefinitely.

### ISSUE THREAD

**Issue by o01eg** [sfackler/rust-postgres#274]
I tries to write and found out `execute` function hang-ups on prepared calls to function. It affects debug and release, stable and dev version. `query` with select from table executes successfully.

Code based on documentation example: https://github.com/o01eg/postgre-test

Function `test_func`:
```sql
CREATE OR REPLACE FUNCTION public.test_func(source_url character varying)
  RETURNS void AS
$BODY$
BEGIN
END
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION public.test_func(character varying)
  OWNER TO postgres;
```

In `pg_stat_activity` it has `idle` state.

Stacktrace on freeze:
```
#0  0x00007ffff74f1433 in epoll_wait () from /lib64/libc.so.6
#1  0x000055555577b51c in mio::sys::unix::epoll::Selector::select (self=0x7ffff7058020, evts=0x7fffffffcb68, awakener=..., timeout=...)
    at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.9/src/sys/unix/epoll.rs:82
#2  0x0000555555775c62 in mio::poll::Poll::poll2 (self=0x7ffff7058020, events=0x7fffffffcb68, timeout=...)
    at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.9/src/poll.rs:1097
#3  0x000055555577584b in mio::poll::Poll::poll (self=0x7ffff7058020, events=0x7fffffffcb68, timeout=...)
    at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.9/src/poll.rs:1061
#4  0x0000555555762331 in tokio_core::reactor::Core::poll (self=0x7fffffffcb68, max_wait=...)
    at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:276
#5  0x000055555556373e in tokio_core::reactor::Core::run<futures::future::and_then::AndThen<futures::future::and_then::AndThen<futures::future::then::Then<alloc::boxed::Box<Future>, futures::future::result_::FutureResult<tokio_postgres::Connection, tokio_postgres::error::Error<tokio_postgres::Connection>>, closure>, alloc::boxed::Box<Future>, closure>, alloc::boxed::Box<Future>, closure>> (self=0x7fffffffcb68, f=...)
    at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:241
#6  0x000055555558f7d3 in postgre_test::main () at /mnt/another/srcs/myGIT/postgre-test/src/main.rs:20
#7  0x00005555557c384b in panic_unwind::__rust_maybe_catch_panic ()
    at /tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/src/libpanic_unwind/lib.rs:98
#8  0x00005555557bb717 in std::panicking::try<(),fn()> () at /tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/src/libstd/panicking.rs:436
#9  std::panic::catch_unwind<fn(),()> () at /tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/src/libstd/panic.rs:361
#10 std::rt::lang_start () at /tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/src/libstd/rt.rs:57
#11 0x000055555558fd43 in main ()
```
tokio-postgres v0.2.3
OS: Gentoo Linux AMD64
PostgreSQL: 9.5.7
Rustc: 1.16.0 and 1.20.0-dev (88c3242ef 2017-06-28)

**Comment by sfackler** [comment]
Thanks for the report! It looks like things hang whenever you execute a statement that returns rows. Looking into a fix now.
