### ISSUE TITLE
Panic when using postgres 0.17.0 with actix-web

### ISSUE THREAD

**Issue by ddeng625** [sfackler/rust-postgres#529]
I'm having a problem with postgres 0.17.0, which causes a panic when used with actix-web. The panic does not occur with postgres 0.16.0-rc2.

```rust
use actix_web::{HttpServer, App};
use postgres::{NoTls, Client};

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let client = Client::connect("db_url", NoTls).unwrap();
    HttpServer::new(move || {
        App::new()
    })
        .bind("127.0.0.1:9090")?
        .start()
        .await
}
```

These are the dependencies I used.
```toml
[dependencies]
actix-rt = "=1.0.0"
actix-web = "=2.0.0-rc"
postgres = "=0.17.0"
tokio = "0.2.6"
```

Here is the panic message.
```
thread 'main' panicked at 'default Tokio reactor already set for execution context', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/io/driver/mod.rs:92:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12: tokio::io::driver::set_default::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/io/driver/mod.rs:92
  13: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  14: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  15: tokio::io::driver::set_default
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/io/driver/mod.rs:89
  16: tokio::runtime::io::variant::set_default::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/io.rs:43
  17: core::option::Option<T>::map
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/option.rs:447
  18: tokio::runtime::io::variant::set_default
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/io.rs:43
  19: tokio::runtime::handle::Handle::enter::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:34
  20: tokio::runtime::blocking::pool::Spawner::enter::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/pool.rs:194
  21: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  22: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  23: tokio::runtime::blocking::pool::Spawner::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/pool.rs:179
  24: tokio::runtime::handle::Handle::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:33
  25: tokio::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/mod.rs:416
  26: postgres::config::Config::connect
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.17.0/src/config.rs:253
  27: postgres::client::Client::connect
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.17.0/src/client.rs:54
  28: postgres_test::main::{{closure}}
             at src/main.rs:6
  29: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  30: std::future::set_task_context
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:79
  31: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/future.rs:43
  32: <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:307
  33: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:139
  34: tokio::runtime::global::with_state::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:100
  35: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  36: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  37: tokio::runtime::global::with_state
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:83
  38: tokio::runtime::global::with_basic_scheduler
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:62
  39: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:122
  40: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/mod.rs:419
  41: tokio::runtime::global::with_state::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:100
  42: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  43: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  44: tokio::runtime::global::with_state
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:83
  45: tokio::runtime::global::with_basic_scheduler
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/global.rs:62
  46: tokio::runtime::basic_scheduler::Spawner::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/basic_scheduler.rs:174
  47: tokio::runtime::spawner::Spawner::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/spawner.rs:30
  48: tokio::runtime::handle::Handle::enter::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:36
  49: tokio::time::clock::Clock::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/time/clock.rs:30
  50: tokio::runtime::time::variant::with_default
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/time.rs:43
  51: tokio::runtime::handle::Handle::enter::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:36
  52: tokio::runtime::blocking::pool::Spawner::enter::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/pool.rs:194
  53: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  54: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  55: tokio::runtime::blocking::pool::Spawner::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/pool.rs:179
  56: tokio::runtime::handle::Handle::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/handle.rs:33
  57: tokio::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/mod.rs:416
  58: tokio::task::local::LocalSet::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:288
  59: tokio::task::local::Scheduler::with::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:381
  60: std::thread::local::LocalKey<T>::try_with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:262
  61: std::thread::local::LocalKey<T>::with
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/thread/local.rs:239
  62: tokio::task::local::Scheduler::with
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:377
  63: tokio::task::local::LocalSet::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/local.rs:287
  64: actix_rt::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/runtime.rs:89
  65: actix_rt::builder::SystemRunner::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/builder.rs:187
  66: postgres_test::main
             at src/main.rs:4
  67: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  68: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  69: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  70: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  71: std::panicking::try
             at src/libstd/panicking.rs:265
  72: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  73: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  74: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  75: main
  76: __libc_start_main
  77: _start
```

I'm not sure where this needs to get resolved, but it seems like something to do with 0.17.0 switching over to tokio 0.2? If so, is there something I can do to prevent this from happening?

**Comment by sfackler** [comment]
If you're in an async function, you shouldn't be using the blocking client interface. `tokio-postgres` is probably a better option.

**Comment by ddeng625** [comment]
Got it. That fixed the issue. Thanks for the help!
