### ISSUE TITLE
Runtime panics when parsing integers/floats from `Numeric` for a basic use case.

### ISSUE THREAD

**Issue by rtviii** [sfackler/rust-postgres#907]
Basically, verbatim [from SO](https://stackoverflow.com/questions/72594101/how-to-parse-a-postgresql-numeric-type-to-rust-native-ones-upon-request?noredirect=1#comment128235517_72594101):

```rust
use postgres::{Client, NoTls, Error, Config, types::FromSql, types::Type};

fn main()->Result<(),Box< dyn std::error::Error>> {

    std::env::set_var("RUST_BACKTRACE", "full");
    let mut client = Config::new().host("localhost").password("password").user("postgres").dbname("regular").port(5432).connect(NoTls)?;
    for row in client.query("SELECT id, price FROM testtable", &[])? {
        let price:f64 = row.get(1);
        println!("{:?}", price);
    }
    Ok(())
}
```
I'm unable to parse `i64` or `f64` (or anything similar for that matter) from PostgreSQL for no obvious reason at all. Created the postgres table with `CREATE TABLE testtable (id int nonzero, price numeric);`. Postgres is of version `psql (PostgreSQL) 12.11 (Ubuntu 12.11-1.pgdg20.04+1)`. 

I _am_ able to print the rows just fine:
```rust
//...
for row in client.query("SELECT id, price FROM testtable", &[])? {
        println!("Row : {:?}", row);
    }

Row : Row { columns: [Column { name: "id", type: Int4 }, Column { name: "price", type: Numeric }] }
Row : Row { columns: [Column { name: "id", type: Int4 }, Column { name: "price", type: Numeric }] }
Row : Row { columns: [Column { name: "id", type: Int4 }, Column { name: "price", type: Numeric }] }
```
but the moment i try to parse an integer/float from the `row.get(1)`  i'm etting the following runtime error (with full stacktrace):

```rust
thread 'main' panicked at 'error retrieving column 1: error deserializing column 1: cannot convert between the Rust type `f64` and the Postgres type `numeric`', /home/rxz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.7.6/src/row.rs:151:25
stack backtrace:
   0:     0x556b9c8ae9ad - std::backtrace_rs::backtrace::libunwind::trace::hda39d6860b2d6f70
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x556b9c8ae9ad - std::backtrace_rs::backtrace::trace_unsynchronized::ha1bfdeb508735a0a
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556b9c8ae9ad - std::sys_common::backtrace::_print_fmt::h4e9e937d66742a36
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x556b9c8ae9ad - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h73a948c4553c4f51
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x556b9c8ce92c - core::fmt::write::ha91e2a0e6cdcb7d1
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/fmt/mod.rs:1194:17
   5:     0x556b9c8ab061 - std::io::Write::write_fmt::heda409ac36864e96
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/io/mod.rs:1655:15
   6:     0x556b9c8b0325 - std::sys_common::backtrace::_print::he8c3809f69ea2342
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x556b9c8b0325 - std::sys_common::backtrace::print::hecbd7b926628aa09
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x556b9c8b0325 - std::panicking::default_hook::{{closure}}::h8fbf7884094b6f2e
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:295:22
   9:     0x556b9c8aff99 - std::panicking::default_hook::h6334d4a28312e99b
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:314:9
  10:     0x556b9c8b08c2 - std::panicking::rust_panic_with_hook::h73dbf64f0060aa58
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:698:17
  11:     0x556b9c8b07a7 - std::panicking::begin_panic_handler::{{closure}}::h57f62f8b0c4aa3d9
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:588:13
  12:     0x556b9c8aee64 - std::sys_common::backtrace::__rust_end_short_backtrace::h3194a80099ffb120
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x556b9c8b04d9 - rust_begin_unwind
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:584:5
  14:     0x556b9c6aebb3 - core::panicking::panic_fmt::h77eb0c9a0a627689
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/panicking.rs:142:14
  15:     0x556b9c6ef532 - tokio_postgres::row::Row::get::hc99236aa806670e1
                               at /home/rxz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.7.6/src/row.rs:151:25
  16:     0x556b9c6bcaab - ppostgres::main::h4c821ea40f797d12
                               at /home/rxz/dev/ppostgres/src/main.rs:9:25
  17:     0x556b9c6b3f0b - core::ops::function::FnOnce::call_once::h32d0b3487bef16f2
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/ops/function.rs:248:5
  18:     0x556b9c6b782e - std::sys_common::backtrace::__rust_begin_short_backtrace::h16c6157217525973
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/backtrace.rs:122:18
  19:     0x556b9c6c0021 - std::rt::lang_start::{{closure}}::h424c04641de31909
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/rt.rs:145:18
  20:     0x556b9c8a727e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8747dac316cfe8b1
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/core/src/ops/function.rs:280:13
  21:     0x556b9c8a727e - std::panicking::try::do_call::ha8cfd36c99c35841
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:492:40
  22:     0x556b9c8a727e - std::panicking::try::h44599ca0771bc4e2
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:456:19
  23:     0x556b9c8a727e - std::panic::catch_unwind::hfc289307f73cb8b7
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panic.rs:137:14
  24:     0x556b9c8a727e - std::rt::lang_start_internal::{{closure}}::h9fadec4e4222aa5a
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/rt.rs:128:48
  25:     0x556b9c8a727e - std::panicking::try::do_call::h742ca90b47c7614a
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:492:40
  26:     0x556b9c8a727e - std::panicking::try::ha8060cd5fe01b8e1
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panicking.rs:456:19
  27:     0x556b9c8a727e - std::panic::catch_unwind::h3548704cd9c5e356
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/panic.rs:137:14
  28:     0x556b9c8a727e - std::rt::lang_start_internal::hc6526c5151dc66ec
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/rt.rs:128:20
  29:     0x556b9c6bfff0 - std::rt::lang_start::h1ece41dbd93b4528
                               at /rustc/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/rt.rs:144:17
  30:     0x556b9c6bcbcc - main
  31:     0x7fc0dce60083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  32:     0x556b9c6aee0e - _start
  33:                0x0 - <unknown>

```
It's a fresh project created with `cargo new` specifically to test this piece of functionality because i ran into this issue elsewhere. 

`Cargo.toml` looks like this:
```toml
[package]
name = "ppostgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.3"
```

For the love of day, what am i missing?
Thank you.

**Comment by sfackler** [comment]
The numeric type is an arbitrary precision value, which is not true of integers or floats in Rust. The rust-decimal crate implements types that can convert to and from numeric: https://github.com/paupino/rust-decimal.

**Comment by rtviii** [comment]
@sfackler Thanks! Is there any performance overhead to using `rust-decimal` that you know of? Trying now..
Also, i've seen so many [examples](https://github.com/jlerche/actix_web_tokio_postgres_example/blob/aff2dee71766d0e09b091314cb9e24632d9d8c3e/src/database/db.rs#L278-L279) using just the native dataypes on github without reimplementing To/FromSql traits... how does that work or am i missing something?

**Comment by rtviii** [comment]
Oh, i guess their tables must not be `NUMERIC`. Late here :\ 
Thanks a lot!
