### ISSUE TITLE
`cargo test` fails from freshly pulled repo

### ISSUE THREAD

**Issue by amab8901** [sfackler/rust-postgres#966]
I followed [these](https://github.com/sfackler/rust-postgres#running-test-suite) instructions, and here's what I get:
<details>
<summary>$ cargo test</summary>

```
    Finished test [unoptimized + debuginfo] target(s) in 0.11s
     Running unittests src/main.rs (target/debug/deps/codegen-122ecb75044f1c16)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/postgres-19e4900cf5116a8f)

running 22 tests
test test::check_send ... ok
test test::binary_copy_out ... FAILED
test test::binary_copy_in ... FAILED
test test::cancel_query ... FAILED
test test::copy_in ... FAILED
test test::explicit_close ... FAILED
test test::nested_transactions ... FAILED
test test::copy_in_abort ... FAILED
test test::copy_out ... FAILED
test test::notifications_blocking_iter ... FAILED
test test::notifications_iter ... FAILED
test test::notifications_timeout_iter ... FAILED
test test::notice_callback ... FAILED
test test::query_prepared ... FAILED
test test::query_unprepared ... FAILED
test test::portal ... FAILED
test test::prepare ... FAILED
test test::transaction_drop_immediate_rollback ... FAILED
test test::savepoints ... FAILED
test test::transaction_drop ... FAILED
test test::transaction_rollback ... FAILED
test test::transaction_commit ... FAILED

failures:

---- test::binary_copy_out stdout ----
thread 'test::binary_copy_out' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:322:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::binary_copy_in stdout ----
thread 'test::binary_copy_in' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:276:87

---- test::cancel_query stdout ----
thread 'test::cancel_query' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:375:87

---- test::copy_in stdout ----
thread 'test::copy_in' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:234:87

---- test::explicit_close stdout ----
thread 'test::explicit_close' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:499:83

---- test::nested_transactions stdout ----
thread 'test::nested_transactions' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:132:87

---- test::copy_in_abort stdout ----
thread 'test::copy_in_abort' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:257:87

---- test::copy_out stdout ----
thread 'test::copy_out' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:301:87

---- test::notifications_blocking_iter stdout ----
thread 'test::notifications_blocking_iter' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:413:87

---- test::notifications_iter stdout ----
thread 'test::notifications_iter' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:393:87

---- test::notifications_timeout_iter stdout ----
thread 'test::notifications_timeout_iter' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:446:87

---- test::notice_callback stdout ----
thread 'test::notice_callback' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Closed, cause: None }', postgres/src/test.rs:488:10

---- test::query_prepared stdout ----
thread 'test::query_prepared' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:27:87

---- test::query_unprepared stdout ----
thread 'test::query_unprepared' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:37:87

---- test::portal stdout ----
thread 'test::portal' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Closed, cause: None }', postgres/src/test.rs:348:87

---- test::prepare stdout ----
thread 'test::prepare' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:16:87

---- test::transaction_drop_immediate_rollback stdout ----
thread 'test::transaction_drop_immediate_rollback' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:107:87

---- test::savepoints stdout ----
thread 'test::savepoints' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:183:87

---- test::transaction_drop stdout ----
thread 'test::transaction_drop' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Closed, cause: None }', postgres/src/test.rs:87:87

---- test::transaction_rollback stdout ----
thread 'test::transaction_rollback' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:67:87

---- test::transaction_commit stdout ----
thread 'test::transaction_commit' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', postgres/src/test.rs:46:87


failures:
    test::binary_copy_in
    test::binary_copy_out
    test::cancel_query
    test::copy_in
    test::copy_in_abort
    test::copy_out
    test::explicit_close
    test::nested_transactions
    test::notice_callback
    test::notifications_blocking_iter
    test::notifications_iter
    test::notifications_timeout_iter
    test::portal
    test::prepare
    test::query_prepared
    test::query_unprepared
    test::savepoints
    test::transaction_commit
    test::transaction_drop
    test::transaction_drop_immediate_rollback
    test::transaction_rollback

test result: FAILED. 1 passed; 21 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `-p postgres --lib`
 
```

</details>

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-postgres#running-test-suite

**Comment by amab8901** [comment]
> https://github.com/sfackler/rust-postgres#running-test-suite

that's literally what I did, as I said in the post -_-

**Comment by sfackler** [comment]
Oh sorry. I'd probably look at what state the docker containers are in.

**Comment by amab8901** [comment]
> Oh sorry. I'd probably look at what state the docker containers are in.

ok but I'm kinda junior so I can't really expand your abbreviated description and fill in the details myself. You probably need to give me a clearer description so I will know what to do

**Comment by sfackler** [comment]
You can start with `docker ps` to see if the container is still running. `docker logs` can show you log messages from the postgres instance.

**Comment by amab8901** [comment]
<details>
<summary>$ sudo docker ps</summary>

```
CONTAINER ID   IMAGE         COMMAND                  CREATED          STATUS          PORTS                                                 NAMES
ca55636608be   postgres:14   "docker-entrypoint.s…"   34 seconds ago   Up 32 seconds   5432/tcp, 0.0.0.0:5433->5433/tcp, :::5433->5433/tcp   rust-postgres-postgres-1

```
</details>

<details>
<summary>$ sudo docker logs ca55636608be</summary>

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2022-12-01 04:34:12.097 UTC [1] LOG:  starting PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-12-01 04:34:12.097 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5433
2022-12-01 04:34:12.097 UTC [1] LOG:  listening on IPv6 address "::", port 5433
2022-12-01 04:34:12.101 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5433"
2022-12-01 04:34:12.106 UTC [25] LOG:  database system was shut down at 2022-11-30 05:03:14 UTC
2022-12-01 04:34:12.113 UTC [1] LOG:  database system is ready to accept connections
```
</details>
Now what?

**Comment by amab8901** [comment]
> I'm not sure. It seems like something is configured weirdly and isn't allowing communication with the container.

ok, thanks for trying to help anyway. Btw maybe it's more appropriate to close it as "not planned" (grey icon) rather than closing as "completed" (purple icon)
